### Variables
@baseUrl = http://localhost:8000
@studyId = 8
@habitId = 21

### 습관 생성
POST {{baseUrl}}/habit
Content-Type: application/json

{
    "name": "매일 알고리즘 1문제 풀기",
    "studyId": {{studyId}}
}

### 습관 목록 조회
GET {{baseUrl}}/study/{{studyId}}/habit/

### 습관 상태 업데이트 (DONE/UNDONE)
PATCH  {{baseUrl}}/habit/{{habitId}}
Content-Type: application/json

{
    "name": "매일 알고리즘 1문제 풀기",
    "status": "DONE"
}

### 습관 삭제
DELETE {{baseUrl}}/habit/{{habitId}}

### 습관 로그
POST {{baseUrl}}/habit/{{habitId}}/log/toggle


### 습관 여러개 업데이트
# PATCH {{baseUrl}}/habit/
# Content-Type: application/json

# [
#      {
#         "id": 1,
#         "title": "매일 알고리즘 1문제 풀기"
#      },
#      {
#         "id": 2,
#         "title": "매일 알고리즘 1문제 풀기"
#      },
#      {
#         "id": null,
#         "title": "매일 알고리즘 1문제 풀기"
#      },
#      {
#         "id": 4,
#         "title": "매일 알고리즘 1문제 풀기"
#      }
# ]

###
PATCH {{baseUrl}}/study/{{studyId}}/habit/
Content-Type: application/json

[
    {
        "id": null,
        "name": "매일 알고리즘 1문제 풀기"
    },
    {
        "id": 22,
        "name": "백준 골드 문제 풀기"
    }
]
